### ISSUE TITLE
 body.slaves.forEach(slave => {

### ISSUE THREAD

**Issue by kxnkxv** [Eimaen/slave-guard#1]
$ node index.js
slave-guard is running...
C:\Users\vapersan\Desktop\slave-guard-main\index.js:34
            body.slaves.forEach(slave => {
                        ^

TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (C:\Users\vapersan\Desktop\slave-guard-main\index.js:34:25)
    at Request.self.callback (C:\Users\vapersan\Desktop\slave-guard-main\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\vapersan\Desktop\slave-guard-main\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\vapersan\Desktop\slave-guard-main\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by Eimaen** [comment]
Это была проблема на стороне приложения. Они начали проверять наличие HTTP-заголовка `Origin` в запросах, тем самым пытаясь фильтровать ботов. Последний коммит должен исправить это.

Также такая ошибка может возникнуть, если токен перестал работать. В таком случае попробуйте получить новый.
