### ISSUE TITLE
Cannot read property 'balance' of undefined

### ISSUE THREAD

**Issue by kxnkxv** [Eimaen/slave-guard#2]
$ node index.js
slave-guard is running...
C:\Users\vapersan\Desktop\slave\slave-guard\index.js:61
                moneyLeft = body.me.balance;
                                    ^

TypeError: Cannot read property 'balance' of undefined
    at Request._callback (C:\Users\vapersan\Desktop\slave\slave-guard\index.js:61:37)
    at Request.self.callback (C:\Users\vapersan\Desktop\slave\slave-guard\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\vapersan\Desktop\slave\slave-guard\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\vapersan\Desktop\slave\slave-guard\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

При этом:
Баланс: 10,838,448
Рабов: -81
Доход в минуту: -20,498

**Comment by kxnkxv** [comment]
Т.е. бага возможно возникла именно из-за отрицательных значений

**Comment by Eimaen** [comment]
> Т.е. бага возможно возникла именно из-за отрицательных значений

Не уверен, что эта проблема возникла из-за отрицательных значений, хотя и не могу это отрицать. Скрипт не тестировался на значениях меньше 0, потому что я не знаю, как такое сделать ;D

Вы можете приложить значение `body` в момент возникновения ошибки?

**Comment by kxnkxv** [comment]
Хотя отрицательные !== undef так что

**Comment by kxnkxv** [comment]
5 минут)

**Comment by kxnkxv** [comment]
{ error: { message: 'Invalid sign 3' } }

**Comment by kxnkxv** [comment]
В общем раньше у тебя в конфиге токен указывался через Barrer ... теперь без него, проблема именно в токене была)

**Comment by Eimaen** [comment]
> В общем раньше у тебя в конфиге токен указывался через Barrer ... теперь без него, проблема именно в токене была)

Только хотел написать. Нужно будет обрабатывать эту ошибку)
